[tool.poetry]
name = "mini-project-back"
version = "0.1.0"
description = ""
authors = ["zsert1 <zsert1@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
